### PR TITLE
Update: Add email to MatchedAddress.php

### PR DESCRIPTION
**Pull request by NilsDelaguardia**
We started having an issue with address fields shifting positions in one of our other projects. 
After investigation, ShipEngine seems to have added email to their expected return for address validation, but hasn't updated their documentation(See below images).

This corrects the issue by adding the expected email field to MatchedAddress.

Screen Shot 2023-09-11 at 1 53 32 PM

### CODE REVIEW

**Comment by iBotPeaches** [comment]
I wonder what an email has to do with an address. This seems odd.

**Comment by NilsDelaguardia** [comment]
> I wonder what an email has to do with an address. This seems odd.

I don't disagree, but I don't think it's any stranger than them returning "name" and "phone".

**Comment by iBotPeaches** [comment]
Sent a question to ShipEngine either way. We could fix tests and patch this, but I'm still not following it. I can see name/phone, but email is a stretch.

**Comment by nicomaurer** [comment]
> Sent a question to ShipEngine either way. We could fix tests and patch this, but I'm still not following it. I can see name/phone, but email is a stretch.

@iBotPeaches I feel like this is Deja Vu when TSO was still with us. Did DevOps@sourcetoad.com (I assume this gets redirected to you) get any email on this at all?

**Comment by NilsDelaguardia** [comment]
> Sent a question to ShipEngine either way. We could fix tests and patch this, but I'm still not following it. I can see name/phone, but email is a stretch.

Sounds good to me. 👍

**Comment by iBotPeaches** [comment]
> Email is a field we added recently as certain carriers(Mostly EU) require it and use it regularly, it is also accepted by most carriers but it isnt needed and can remian null or empty if you dont want to put data there.

From ShipEngine @NilsDelaguardia - so I guess lets get this fixed and merged.

**Review by iBotPeaches — APPROVED** [review]

**Review by nicomaurer — APPROVED** [review]

**Review by erik-perri — APPROVED** [review]

**Pull request merged**
